/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "nlpservice_constants.h"

namespace nlpservice {

const nlpserviceConstants g_nlpservice_constants;

nlpserviceConstants::nlpserviceConstants() {
}

} // namespace

