/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef nlpservice_CONSTANTS_H
#define nlpservice_CONSTANTS_H

#include "nlpservice_types.h"

namespace nlpservice {

class nlpserviceConstants {
 public:
  nlpserviceConstants();

};

extern const nlpserviceConstants g_nlpservice_constants;

} // namespace

#endif
